name: Nexcavate
version: '${project.version}'
main: me.char321.nexcavate.Nexcavate
api-version: 1.16
depend: [ Slimefun ]
authors: [ char321 ]
description: A Slimefun Addon about rebuilding the ancient civilization.

commands:
  nexcavate:
    aliases: [nex]